feat: Scripts was added to simplify the work environment creation
googleapis/python-retail pull request #187
Opened 2022-03-11 12:55 UTC by t-karasova

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-retail/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-03-11 14:45 UTC, kweinmeister requested changes

2022-03-11 14:45 UTC, kweinmeister commented on samples/interactive-tutorials/user_environment_setup.sh
> +# get the project_id from gcolud config
gcloud config

2022-03-11 14:45 UTC, kweinmeister commented on samples/interactive-tutorials/user_environment_setup.sh
> +#!/bin/bash
Please add copyright headers to both files

2022-03-11 14:45 UTC, kweinmeister commented on samples/interactive-tutorials/user_environment_setup.sh
> +# set the key as GOOGLE_APPLICATION_CREDANTIALS
Change to CREDENTIALS (on 2 lines)

2022-03-11 14:45 UTC, kweinmeister commented on samples/interactive-tutorials/user_environment_setup.sh
> +# uppload your service account key file
upload

2022-03-11 14:45 UTC, kweinmeister commented on samples/interactive-tutorials/user_import_data_to_catalog.sh
> +bucket_name="${temp% was created}"
Is there supposed to be just one %?

2022-03-14 12:54 UTC, t-karasova commented on samples/interactive-tutorials/user_environment_setup.sh
> +# get the project_id from gcolud config
fixed

2022-03-14 12:56 UTC, t-karasova commented on samples/interactive-tutorials/user_import_data_to_catalog.sh
> +bucket_name="${temp% was created}"
exactly

2022-03-14 14:24 UTC, kweinmeister approved these changes

2022-03-14 17:18 UTC, chenlei1216 approved these changes

2022-03-14 19:00 UTC, parthea approved these changes

2022-03-15 13:17 UTC, merged